owner: idammi
repo: status

assignees:
  -  idammi

sites:
  - name: SocialGenius.net
    url: https://www.socialgenius.net
    icon: https://app.socialgenius.net/favicon.ico
    maxResponseTime: 30000
  - name: SocialGenius CRM
    url: https://app.socialgenius.net/login/
    icon: https://app.socialgenius.net/favicon.ico
    maxResponseTime: 30000
  - name: SocialGenius Store
    url: $SOCIALGENIUS_STORE
    icon: https://store.socialgenius.net/wp-content/uploads/2021/02/cropped-favicon-192x192.png
    maxResponseTime: 30000

status-website:
  cname: status.socialgenius.net
  logoUrl: https://app.socialgenius.net/favicon.ico
  favicon: https://app.socialgenius.net/favicon.ico
  name: SocialGenius Status
  introTitle: "**SocialGenius** uptime monitor and status page"
  introMessage: This status page uses **real-time** data from [SocialGenius](https://www.socialgenius.net) servers.
      
commitMessages:
  commitAuthorName: "SocialGenius Bot"
  commitAuthorEmail: "dami@socialgenius.net"
